In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1,])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

In [4]:
print(a+b)
print(a-b)
print(a*b)


[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [5]:
# creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [7]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [8]:
print(a2.ndim)
print(a3.ndim)

2
3


In [9]:
print(a2.dtype)

int64


In [10]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
# random lib.used to create 2d arrays
np.random.randint(1,11, size=(2,3))

array([[5, 3, 2],
       [4, 8, 1]], dtype=int32)

In [14]:
# random lib.used to create 3d array
np.random.randint(1,11,size=(3,2,3))

array([[[ 7,  7,  6],
        [ 6,  9, 10]],

       [[ 2,  3,  6],
        [ 7,  3,  1]],

       [[ 3,  7,  6],
        [10,  9,  6]]], dtype=int32)

In [15]:
x=np.random.randint(1,21,size=(2,2))
y=np.random.randint(1,21,size=(2,2))
print(x)
print(y)

[[17  5]
 [ 4 16]]
[[15 15]
 [15  2]]


In [16]:
print(x+y)
print(x-y)
print(x*y)

[[32 20]
 [19 18]]
[[  2 -10]
 [-11  14]]
[[255  75]
 [ 60  32]]


In [17]:
#matrix multiplication
#lst method
print(x@y)

[[330 265]
 [300  92]]


In [18]:
# 2nd method
np.dot(x,y)

array([[330, 265],
       [300,  92]], dtype=int32)

In [19]:
# product of all element present in matrix
x.prod()

np.int64(5440)

In [20]:
# avg
x.mean()
y.mean()

np.float64(11.75)

In [21]:
print(x)

[[17  5]
 [ 4 16]]


In [22]:

b = x.mean(axis=0) #column wise
print(b)

[10.5 10.5]


In [23]:
c = x.mean(axis=1) #row wise
print(c)

[11. 10.]


In [24]:
x.sum()

np.int64(42)

In [25]:
print(x.std())#standard deviation
print(x.var())#variance

6.020797289396148
36.25


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr,75))

5.0
3.0
7.0


In [27]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[57 55 21 88]
 [71 57 87 47]
 [61 85 84 83]
 [73 42 82 87]]


In [28]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[57 55 21 88 71 57 87 47]
 [61 85 84 83 73 42 82 87]]
8x2
[[57 55]
 [21 88]
 [71 57]
 [87 47]
 [61 85]
 [84 83]
 [73 42]
 [82 87]]


In [29]:
print(arr2)

[[57 55 21 88]
 [71 57 87 47]
 [61 85 84 83]
 [73 42 82 87]]


In [34]:
print(arr2[0])#0th row
print(arr2[0,1])#0th row 1st column
print(arr2[-1])#last row
print(arr2[:3])#0th to second row
print(arr[1:])#1st to last row

[57 55 21 88]
55
[73 42 82 87]
[[57 55 21 88]
 [71 57 87 47]
 [61 85 84 83]]
[2 3 4 5 6 7 8 9]


In [35]:
arr2>50# element present in array is greater than 50

array([[ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True]])

In [40]:
y = arr2[arr2>50]
z = y.reshape(4,3)
print(z)

ValueError: cannot reshape array of size 13 into shape (4,3)